language: php

php:
  - 7.0

sudo: false

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash
  - cp .env.travis .env
  - chmod 0755 .env
  - php artisan key:generate
  - php artisan config:clear
  - mysql -e 'create database homestead_test;'
  - set +H

script:
  - vendor/bin/phpunit

notifications:
  email: false
